# Generated by Django 5.1.4 on 2025-01-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts/images')),
                ('createdate', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=150, unique=True)),
            ],
        ),
    ]
