# Generated by Django 5.1.4 on 2025-01-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_words_alter_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='gameresult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('correctanswer', models.CharField(max_length=100)),
                ('useranswer', models.CharField(max_length=100)),
                ('iscorrect', models.BooleanField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
