# Generated by Django 5.1.4 on 2025-02-03 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0007_quiz_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='createdate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
