# Generated by Django 5.1.4 on 2025-02-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0008_alter_quiz_content_alter_quiz_createdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='week',
            field=models.IntegerField(null=True),
        ),
    ]
