# Generated by Django 5.1.4 on 2025-02-09 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0009_quiz_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='week',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
