# Generated by Django 5.1.4 on 2025-02-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0010_alter_quiz_week'),
    ]

    operations = [
        migrations.CreateModel(
            name='gameresult2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iscorrect', models.JSONField(default=list)),
            ],
        ),
    ]
