# Generated by Django 5.1.4 on 2025-02-16 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0014_leaderboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='speechquiz2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts/images')),
                ('data', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
