# Generated by Django 5.1.4 on 2025-02-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0017_useractivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='badges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('score', models.IntegerField(null=True)),
            ],
        ),
    ]
